### ISSUE TITLE
Harden Instant Status

### ISSUE THREAD

**Issue by maxbadrak** [jvmahon/homebridge-homeseer#18]
If HomeSeer becomes unavailable and the TCP connection to the ASCIIPort disconnects, the instant status silently stops working. It would be great if there was a periodic connection retry. (In my setup the VM on which HS runs is backed up in the middle of the night. During the backup the VM is paused, and the connection breaks)

**Comment by jvmahon** [comment]
That's a good suggestion. I suspect (maybe) it could be handled by the client.on('error'... code at lines 428-438 of the index.js file. I'll experiment with that a bit for the next release.

In the meantime, consider having your backup script shut down homebridge and then restart it after the backup. I use homebridge on both Windows and Linux and on Widows and I set task scheduler to re-start homebridge  both on system boot and if Windows detects it isn't running. Similarly, on Linux, I use the systemctl daemon to start on boot and then restart homebridge if it fails. 

Even if I can get the automatic retry into the next update, it may still be a good idea to shut homebridge down purposefully and the-restart, rather than try to recover from a failure.

**Comment by maxbadrak** [comment]
Fair. If Homebridge failed in case this connection was broken, it would make it easier to restart. Right now it's just quietly loosing instant status. I suppose I could finagle something with cron and netstat (to check for an established connection), and then restart homebridge... But having an option to allow homebridge to fail would be nice. :)

**Comment by jvmahon** [comment]
Understood. I will try to look at it soon. Conceptually, the fix seems simple, but often things that seem simple don't work out that way. I may get to it this weekend, but will almost certainly know within a week if I can get it to work. Assuming I can get some code to handle this error, I assume you'd be willing to test it out on your setup before I roll it into a general release.

**Comment by jvmahon** [comment]
I think I have this working already.  After a connection failure, the code will attempt to re-connect every 30 seconds until it can connect.  It will display an updated error message every 30 seconds if it doesn't connect. 
Please install the "test" code using 'git' and let me know if it works for you. If it works, I'll clean up the error messages (they are not clear at the moment) then publish it to npm. To install:
     npm -g install git://github.com/jvmahon/homebridge-homeseer#AutoRecover

**Comment by jvmahon** [comment]
Published as version 2.3.3
To use the published version, you need to execute:

         npm -g install homebridge-homeseer-plugin-2018

Closing this comment. Let me know if you have any issues.
