### ISSUE TITLE
homebridge not working

### ISSUE THREAD

**Issue by BillBingaman** [jvmahon/homebridge-homeseer#23]
getting error
'homebridge' is not recognized as an interneal or external command, operable program or batch file.

Any suggestions, tried reinstalling but it just said updated package.

**Comment by jvmahon** [comment]
After you installed Homebridge, did you completely exit the Windows command window and then use an entirely new just-opened command window to try and start homebridge?   If you don't do that, Windows won't find homebridge.  See first paragraph of Windows 10 Install instructions in Section F.

If that doesn't work, execute:
    npm -g ls --depth=0

This will list the npm packages that you have installed. Do you see homebridge listed?

I'm going to be unavailable for the next few hours, but if you continue to have problems, post another message and I can try to help this evening.

**Comment by BillBingaman** [comment]
This is what I got.

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Homeseer>npm -g ls --depth=0
C:\Users\Homeseer\AppData\Roaming\npm
+-- homebridge-homeseer-plugin-2018@2.3.3
`-- windows-build-tools@2.2.1


C:\Users\Homeseer>homebridge
'homebridge' is not recognized as an internal or external command,
operable program or batch file.

Thanks,
Bill Bingaman
President
ComputerNet Services
309 Court Ave, Suite 801
Des Moines, IA 50309
515-223-9300
Bill@computernetpro.com

Web Site
www.computernetonline.com

**Comment by jvmahon** [comment]
Bill,
You're almost there! You installed the plugin and the build tools, but homebridge itself needs to be installed (t looks like you missed section "E" of the install instructions:  https://github.com/jvmahon/homebridge-homeseer/wiki/Windows-10-Installation )(I've now gone back and emphasized the homebridge install step in these instructions so it stands out a bit better).

You should be able to fix this by executing:

      npm -g install homebridge


Then continue with step "F" if the Windows 10 install instructions.

If all is now O.K., then please let me know and close this comment. Otherwise, let me know and I'll try to help a bit more.

**Comment by BillBingaman** [comment]
Ok thanks, I thought when I installed the 2018 plugin I was doing that.  I will mess with it more tomorrow and Monday.  Might want to keep this open for now.

Thanks,
Bill Bingaman
President
ComputerNet Services
309 Court Ave, Suite 801
Des Moines, IA 50309
515-223-9300
Bill@computernetpro.com

Web Site
www.computernetonline.com
