### ISSUE TITLE
Window Coverings Open and close is incorrect

### ISSUE THREAD

**Issue by RienduPre** [jvmahon/homebridge-homeseer#25]
Hi I'm using the Window Coverings feature, but when I open my Window Covering Homekit says it's closed and the other way around.
In HomeSeer value 0(zero) is "open" and value 255 is "closed"

**Comment by jvmahon** [comment]
Hi,
Other users' have window coverings where 255 is open, 0 is closed.  
To handle this, I've published a new version 2.3.6 which allows the user to specify the open and closed values. In your case, you can set up your window coverings with  "openValue":0, "closedValue":255 parameters specified in your config.json file.

Note that SecuritySystems are now also supported.

**Comment by RienduPre** [comment]
Thank you !!!!

**Comment by shereefalkady** [comment]
@jvmahon hello --- even when i set the open value to 100 -- if i ask it to open, it goes to 99 not 100

my shades only respond to 10,20......90,100.... 
they cant do 99% so they dont open

**Comment by shereefalkady** [comment]
@jvmahon i have insteon open close modules - that work perfectly through homeseer


i have homebridge config as follows:

{"type": "WindowCovering","name": "Window Shutter",	"ref": 49,"binarySwitch":false,	"openValue": 100,"closedValue": 0},



However whenever i give the homekit command to open, the following is the output:
[11/9/2018, 11:19:45 AM] [HomeSeer] Transmitting to HomeSeer device: 49, a new value: 99

my device does not respond to 99 - it must be 100 to open

**Comment by shereefalkady** [comment]
@jvmahon to add: if i ask homekit to do 10 20 30 40 50 60 70 80 90 percent it performs perfectly....
but when i ask it to "open" -- it send 99 - which my devices dont respond to

**Comment by jvmahon** [comment]
Thanks. I understand now. I think this is an easy fix - I'll take a look this weekend.

**Comment by shereefalkady** [comment]
@jvmahon thanks -appreciated

**Comment by shereefalkady** [comment]
@jvmahon thank you ... works like a charm

**Comment by jvmahon** [comment]
Update now published on npm as version 2.3.16

**Comment by shereefalkady** [comment]
@jvmahon *applause* thank you

**Comment by shereefalkady** [comment]
@jvmahon hello again... so i am using rfxcom plugin... i have somfy shades on them working great with homeseer .... however when i add them to homebridge-homeseer they arent responding... i get the following:   
"** Warning - Possible Illegal value for window covering setting
** Warning - Possible Illegal value for window covering setting"

same config works with my insteon open close shades - but the somfy shades from rfxcom are giving me a hard time....

**Comment by shereefalkady** [comment]
@jvmahon note - unlike the insteon shades (which show controls 100/90/80/etc...)
                                              somfy shows Open/Close/Stop

**Comment by shereefalkady** [comment]
@jvmahon stop is basically any percentage other than 100 or 0 - 100 isopen - 0 is close

**Comment by jvmahon** [comment]
Can you post a picture a screen shot (or, even better, using Chrome browser, do a Ctrl+P and Save to PDF) of the HomeSeer "Status Graphics" page for the Somfy shades?

Do they work despite the warning?

I'm thinking that instead of adding the Shades as a Window Covering, it might be possible, as an interim solution, to add them as a Switch which would give you Open / Close ability, though Siri might not work properly with them.

**Comment by shereefalkady** [comment]
@jvmahon even with the homebridge-rfxcom it works the same - makes 3 switches one each for open / close / stop  ....
the tahoma and mylink bridges allow me to use them as open 100% close 0% and anything else is stop...
but the rfxcom seems to make it physical remote button controls....

ill post a screenshot now - ( i can cancel the program button altogether - not required)
and if it can be a shade that transmits open on 100 close on 0 and stop on anything in between it would be perfect

**Comment by shereefalkady** [comment]
![rfx](https://user-images.githubusercontent.com/33227062/54523211-02047980-4980-11e9-9f46-9166a6627c63.png)

**Comment by shereefalkady** [comment]
@jvmahon oh -- also it does not work despite the warning....

**Comment by jvmahon** [comment]
O.K., I think this may be workable using a virtual device as an intermediate step in the control of the shades.

First, create a "Virtual" binary switch in HomeSeer.

Then you will need to create 4 events. 
A first that triggers when the virtual switch is turned On, for this you will create a device control action that controls your shades to Open.
A second that triggers when it is turned Off, this will then have a device control action that controls your shades to Close
A third that triggers when your shade's Open button is "pressed" or open is otherwise achieved. This will then have a device control action that turns the virtual switch to "On" so that the virtual switch stays in Sync.
A fourth that triggers when your shades "Close" button is pressed or the close state is otherwise achieved, this will have a device control action to turn your virtual switch to the "Off" position so it stays in sync with your shades.

Then, in your homebridge config.json, use the reference of the HomeSeer virtual switch you created as the Window shade device, rather than the actual widow shade device.  This general technique of using a virtual device as an intermediary was described in the Wiki here: 

[https://github.com/jvmahon/homebridge-homeseer/wiki/Supporting-non--ZWave-Devices-and-Plugin-values-by-Mapping-to-a-Virtual-HomeSeer-Device](url)

**Comment by shereefalkady** [comment]
@jvmahon ill try that - but wouldnt that be too slow

**Comment by jvmahon** [comment]
No, I don't think so. Events generally process very fast. I've use that technique without any delay issue.

Also,  I just noticed you said your shade controller makes 3 buttons (Open / Close / Stop). I realized these may act like "momentary" buttons in which case there may not be any "true" feedback of shade position from your controller, if that's the case, you may need to "fake" 3 momentary type buttons.

A way to "fake" 3 momentary buttons in HomeKit is to make 3 virtual devices (Switches) corresponding to Open, Close, Stop.  For each of these, you would have an event that activates the corresponding Open, Close, Stop for your Somfy when the switch is turned "On". The last Action in each event is to turn the virtual switch back to the "Off" position. Thus, each switch would act like a Temporary toggle which the user can turn "On", but which always returns to the "Off" position.

**Comment by shereefalkady** [comment]
@jvmahon AMAZINGGG!!!! virtual device works instantly ...

made 3 events - all that just respond to the virtual dimmable switch....
if VDS on - shade up
if VDS off - shade down
id VDS 1-99 - shade stop

and yes there is no feedback its somfy rts ((however it is not a problem - they have no physical controllers other than homekit))

**Comment by jvmahon** [comment]
Glad that worked for you.

As a final suggestion, it might be visually nicer if you made "almost on" and "almost off" activate the On / Off events and if "stop" always displayed the dimmer slider mid-level rather than near the top or bottom.  

For example, if dimmer is set to 85% or above, trigger your On event and as the last step in that event, set the dimmer slider to the "full On" value. Similarly, if dimmer is 15% or below, Trigger the Off event and set the dimmer slider to fully off. And for the Stop event,  trigger that on 16-84% and then as its final step, set the slider to the 50% level.  If you do this, you may need to set the "Cannot Re-Run For" option setting for each event to something like 5 seconds just to be sure that you don't re-trigger the event by adjusting the virtual dimmer device from within the event.
