### ISSUE TITLE
Error Since I updated to the latest version

### ISSUE THREAD

**Issue by RienduPre** [jvmahon/homebridge-homeseer#28]
Hi,

I'm very glad the Alarm system is added, but since I updated to the latest version I get this error.

My config.json is still the same as before the upgrade.

 [HomeSeer] Fetching HomeSeer devices.                                                                                            
[2018-3-20 06:36:25] [HomeSeer] HomeSeer status function succeeded!                                                                                   
Error setting up Devices: TypeError: Cannot read property 'ref' of undefined                                                                          
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'ref' of undefined Check if
 HomeSeer is running, then start homebridge again.                                                                                                    
(node:34) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will termi
nate the Node.js process with a non-zero exit code.

**Comment by RienduPre** [comment]
Forget it, I completely rewrote the Config.json and now the error is gone. 

don't know what caused this....

**Comment by jvmahon** [comment]
Glad you got it working!

As an FYI - the plugin now checks every line of the config.json file. If you use a parameter name that isn't supported, it is designed to throw an error. The previous plugin didn't do that, but I took the approach that its better to stop everything and make the end-user correct the config.json on startup, rather than have a crash during run time.  What's strange here is that if that is happening, the plugin is supposed to tell you the line where the error occurred, so I'm not sure what happened here.  If you have any idea what line in the config.json caused this (and what you did to fix it), let me know -- or if you can send me the 'broken' and the 'fixed' config.json, I"ll take a look.  I'd like to fix the plugin to present a clearer error message.

**Comment by RienduPre** [comment]
Ok clear
