### ISSUE TITLE
Window Sensors

### ISSUE THREAD

**Issue by darrenmcuk** [jvmahon/homebridge-homeseer#38]
So have tried to put one of window sensors into the system. However, its not detecting that the window is Open/Closed. Now this maybe be due to the HomeSeer config:

value 22 = open
value 23 = closed

I tried setting : "onValues":[1,1.255] but got an error stating its not supported. So not really sure how to fix this?

Thanks for your help.

**Comment by jvmahon** [comment]
Yes, it is due to the HomeSeer configuration. I assume you are using type "ContactSensor" which is treated as a simple binary sensor with 0 = closed, and anything else = open.

What type of sensor is this?  I've never seen one with 22= open, 23= closed.

**Comment by darrenmcuk** [comment]
Its a Fibaro Sensor. Darn silly if you ask me. Yes using the "ContactSensor" type. Tried to do this:

			  {
				"ref":3823,
				"type":"ContactSensor",
				"name":"Office RH Large Window",
				"batteryRef":3821,
			        "batteryThreshold":5,
				"onValues":[22]
				}

**Comment by jvmahon** [comment]
What's the model # of the sensor?

Can you send an image of (1) the HomeSeer web page showing all the devices created for the sensor. Usually that includes a 'root' device and several associated devices; (2) for the device you are trying to use (i.e., "ref":3823), provide images of (a) its "Advanced" tab, and (b) its "Status Graphics" tab (I just need the "value" section here, I don't need the Graphics section.

Also, a clarification in response to your first post, the json format used in homebridge plugins does not support defining ranges, so if you have something like [1.255] it does not mean "all numbers between 1 and 255" it means the specific decimal number 1.255 ;  if you want to specify a range of numbers between brackets, each much be individually listed, so the range 1 through 255 would have to be listed [1, 2, 3, 4, 5, and so on until 253, 254, 255]

It may be easy for me to address your specific issue using an "offValues" parameter to specify an array of values  of "off" (for most devices, there is only a single off value '0', so its easiest to specify the off values rather than the many possibilities for 'on').  Since the switches are binary, on is, by default, anything that isn't an "off" value. Make sense?

**Comment by darrenmcuk** [comment]
Hope these help..
![status](https://user-images.githubusercontent.com/33957097/38423941-5499bfa0-39a7-11e8-9972-669cf573a39a.jpeg)
![advanced](https://user-images.githubusercontent.com/33957097/38423944-58c2750e-39a7-11e8-8a06-e0dfe6c7253c.jpeg)
![window status](https://user-images.githubusercontent.com/33957097/38423948-5d2bbb64-39a7-11e8-8a05-2b4b14bd32b1.jpeg)

**Comment by darrenmcuk** [comment]
Just to add only added this device a few mins ago to test...so I guess battery status has not yet reported in

**Comment by jvmahon** [comment]
You didn't send the model # of the sensor, but I assume its the FGDW-002.

I had a look at the manual for the FGDW-002 (https://manuals.fibaro.com/content/manuals/en/FGDW-002/FGDW-002-EN-T-v1.1.pdf) and according to that, by default, it does send 0 for closed / 255  for open, which are the expected values.  

But the defaults could have been changed!

If you look at page 11 of the Advanced Parameters section of that manual, you will see that the open and closed values are controlled by Z-Wave setting parameters 12 and 13. It appears that something has gotten your contact sensors off of their defaults. From the sensor's Root device, Z-Wave tab, in the "Settings" section, you should be able to select each parameter  (one at a time; leave the "Value(Decimal)" field blank to see the current settings) and then click "set" to get its current value. You can then re-set Closed to 0, Open to 255 by putting the correct value in the value field. You may then need to re-audit the node.

Let me know if this works for you.

**Comment by jvmahon** [comment]
In addition to the advice given above, I have also added an "offValues" parameter which can resolve your issue.

In your config.json, you would add the following entry to your ContactSensor entry to set its off value at 22:
         "offValues":[22]

Install the updated plugin using:

     npm -g install homebridge-homeseer-plugin-2018

Note the new version much more carefully checks the config.json file for inconsistencies or for incorrect parameter usage, so you may have to correct your config.json on the first run.

I think this resolves your concern, so I'm closing this issue. Re-open if a concern remains.

**Comment by darrenmcuk** [comment]
Does the trick nicely...many thanks!

**Comment by bradhs** [comment]
I ran into this issue as well. But it is with the Sensative Z-Wave Plus Ultra Thin Door/Window Contact Sensor Strips Guard found here: https://www.amazon.com/gp/product/B01LWMTUI8/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

Just in case anyone else gets stuck this is what the accessory ContactSensor needs to look like.  Replace with your ref and batteryRef

"accessories": [
                {
                    "type": "ContactSensor",
                    "ref": 11,
                    "batteryRef": 12,
                    "batteryThreshold": 40,
                    "offValues": [
                        0,
                        23
                    ]
                }
            ]

**Comment by bradhs** [comment]
I ran into this issue as well. But it is with the Sensative Z-Wave Plus Ultra Thin Door/Window Contact Sensor Strips Guard found here: https://www.amazon.com/gp/product/B01LWMTUI8/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

Just in case anyone else gets stuck this is what my accessory ContactSwitch looked likes:

"accessories": [
                {
                    "type": "ContactSensor",
                    "ref": 1381,
                    "batteryRef": 1380,
                    "batteryThreshold": 40,
                    "offValues": [
                        0,
                        23
                    ]
                }
            ]
