### ISSUE TITLE
poll parameter in config.json ignored?

### ISSUE THREAD

**Issue by rrman** [jvmahon/homebridge-homeseer#41]
First, I wanted to say this is a great plug-in! Device status changes in HomeSeer are immediately reflected in my iOS Home app! I posted the following issue in HomeSeer (https://forums.homeseer.com/showpost.php?p=1362480&postcount=51) but not sure if that's the best place to ask.

Given that the status is updated immediately, I don't think I need polling to be done every 60 seconds. I run three homebridge services in the same VM, and I'm trying to minimize the amount of polling done by the homebridge services. So, I added the "poll" parameter to my config.json files (based on following the sample config.json you posted):

...
"ASCIIport":11000,
"poll":120,

"accessories":
...

I tried 3600 (1 hour) and also 120 for "poll". However, the "poll" value isn't being used. I have the following output, which shows polling is still done every 60 seconds:

Apr 21 10:04:16 homebridge homebridge[1590]: [2018-4-21 10:04:16] [HomeSeer] Successfully connected to ASCII Control Interface of HomeSeer. Instant Status Enabled.
Apr 21 10:04:16 homebridge homebridge[1590]: [2018-4-21 10:04:16] [HomeSeer] Reducing HomeSeer polling rate to: 60 seconds.
Apr 21 10:05:16 homebridge homebridge[1590]: [2018-4-21 10:05:16] [HomeSeer] Poll # 1: Retrieved values for 1 HomeSeer devices.
Apr 21 10:06:16 homebridge homebridge[1590]: [2018-4-21 10:06:16] [HomeSeer] Poll # 2: Retrieved values for 1 HomeSeer devices.
Apr 21 10:07:16 homebridge homebridge[1590]: [2018-4-21 10:07:16] [HomeSeer] Poll # 3: Retrieved values for 1 HomeSeer devices.
...

Did I not specify the poll parameter properly?

Thanks,

randman (user id in HomeSeer forum).

**Comment by rrman** [comment]
Thank you very much for the info. Yes, I also checked the CPU performance of my Homebridge VM and I don’t see any impact on CPU at all. I also really like how the plugin reestablishes its ASCII connection when HomeSeer is restarted but Homebridge remains running (not sure how many reattempts is done before it gives up but Homebridge reconnected after HomeSeer was down for 5 minutes). 

Again, GREAT job on this plug-in and thank you!!

**Comment by jvmahon** [comment]
You're welcome.   If HomeSeer goes down, it attempts a re-connection every 30 seconds indefinitely.  The time for re-connect is set at line 394 of index.js  (this failure scenario is another instance where the polling is needed to re-synchronize!)

The only caveat to the HomeSeer connection failure recovery is that the plugin must connect when it first starts or it throws an error and shuts down. It can't recover from a "first try" failure because it needs to access HomeSeer to pull initialization data on startup. After the first startup, it will recover from HomeSeer failure.  I suppose I could add code to recover from the "first try" failure, but I decided it wasn't worth my efforts.

Glad you are finding this useful. Best regards.

**Comment by jvmahon** [comment]
Also, as an FYI - if you are experimenting with polling times, even though the polling seems to have little or no CPU impact, I also didn't want to poll too often. I found that Homebridge and Siri become sluggish if you poll too much (my testing was that setting a poll period less than 5 seconds became a problem). I am guessing this may be due to the passing of update data between HomeBridge and the Apple TV which becomes the choke point for the Siri control. As I've set it, all the timing seems to work well for me to keep everything responsive.
