### ISSUE TITLE
Error instaling

### ISSUE THREAD

**Issue by mugen5** [jvmahon/homebridge-homeseer#42]
I tried installing and when I get to the part of installing hombridge I get error MSB600: "CL.exe" exited with code 1073741515. I'm running windows 7 home 64 bit. I did open a new command prompt and did also verified and bonjour sdk is installed in the correct location. Log also attached. Any ideas 
[2018-05-01T20_46_25_771Z-debug.log](https://github.com/jvmahon/homebridge-homeseer/files/1965298/2018-05-01T20_46_25_771Z-debug.log)

**Comment by mugen5** [comment]
npm -g install mdns gives the same error which is actually 6006 not 600.

command prompt was in administrator. OpenSSL was installed however the link provided doesn't work so I just google searched and found it. Could be a bad one, it is version 1_0_2. Additionally at the end of the installation I had to chose a donation option which I did. Nothing happened after that, so I thought. I just noticed that internet explore opened minimized for me to complete donation. Considering I didn't download from link provided, is it normal and/or safe to pay this donation. I don't mind just want to make sure.

**Comment by mugen5** [comment]
Windows build was installed. Didn't notice any errors but wasn't really looking for any either. When I try uninstall i get no "such file or directory" in the command prompt. When i re install I don't get any errors. Tried again to install homebridge and still get error. 

I tried installing on my laptop which is also windows 7 64 bit. Installed fine and the test homebridge displayed QR code so this doesn't appear to be windows 7 specific.

**Comment by mugen5** [comment]
I uninstalled nodejs and deleted "npm" and "npm-cache" folders. Even uninstalled openssl. Re did the installations and when I get to install homebridge i get the same errors. Not sure if this is related at all but when I restarted my PC i got an "Icloudservices.EXE" error. Never got this before. Tried reinstalling icloud but still get the same error. Again not sure if this is related or not, just wanted to point it out in case it was.

**Comment by mugen5** [comment]
Attached is everything that comes up in the cmd. Perhaps there will be something else there that sticks out. 

Otherwise it leaves me with a few options. 1. reinstall windows. 2. is there a way to run this from my laptop even-though homeseer is on another machine. 3 Hope and pray that homeseer or someone makes a homeseer plugin wink wink :). 
[cmd.txt](https://github.com/jvmahon/homebridge-homeseer/files/1971502/cmd.txt)

**Comment by mugen5** [comment]
Actually I might try something else. I have Raspberry Pi sitting on the shelf. Never got around to play with it. The install seems straight forward.  Just trying to figure out what OS to put on the RPI. Any suggestion?

**Comment by jvmahon** [comment]
I have Homebridge running on both a Windows setup (HomeBridge and HomeSeer on the same computer) and a Raspberry Pi setup. I'm using the Raspberry Pi because I have my "real" home security system connected to its GPIO pins and use the Pi to trigger sensor accessories in HomeBridge (this setup does not interface to HomeSeer!). I do find the Windows system less trouble to set up (quite the opposite of your experience right now!).  On the Raspberry Pi, I have often found difficulty with file permissions during installations (you'll need to be reasonably knowledgeable about Linux permissions to get everything working). See the Wiki entry I made on installing on Raspberry Pi -  If you run into trouble, I won't be able to offer much guidance beyond that as I don't have a deep enough Linux installation (though my Windows guidance didn't exactly get you there either!). That being said, once Homebridge is installed on the Pi it runs fine.  On Raspberry Pi, I have installed the latest version of Raspbian.

**Comment by mugen5** [comment]
Well then maybe my best option(before re installing windows) is just keep it on my laptop. It does stay on all the time. It's getting old and can run slow at times. I can try and if it I don't see any issues leave it. I did finish the install on it last night and had the homeseer pc address in the config.json file as mentioned above. Even thought I have some devices set up in the config file when I connected homekit to homebridge I didn't get any devices appear in homekit. I'll try again tonight and see if i can figure why. I'll let you know how I make out.

**Comment by jvmahon** [comment]
I don't have anything else to suggest, so I'm going to close out this comment for now. Re-open if you need to ask another question.

**Comment by mugen5** [comment]
Yes. and to verify i checked and there is folder called homeseer-homebridge-plugin-2018 in the node modules folder

**Comment by mugen5** [comment]
config.json file wasn't named properly. I was able to get it to work and get devices on the app and control them. However I get a lot devices/homebridge not responding. Sometimes for long periods of time. Then i get response again.

**Comment by jvmahon** [comment]
Make sure you have the HomeSeer ASCII Interface enabled. See https://github.com/jvmahon/homebridge-homeseer/wiki/Enable-Instant-Status-(HomeSeer-ASCII-Port)
Be sure to re-start HomeSeer and then Homebridge after enabling this. 

I assume you have an Apple TV in your home. Check that it has been updated to the latest TVOS version. Similarly, check that your iOS devices have all been updated.

Also, this may not be a homebridge problem. I sometimes have that problem with native HomeKit device. I'm guessing here, but I understand that iOS sometimes communicates to HomeKit devices and bridges directly with the devices or the bridge and sometimes communicates via the Apple TV. I think there may be delays when it does a switchover between the direct and via-Apple TV communications methods. Just a guess.

Finally, my own setup occasionally has a lengthy delay when updating This typically happens after a homebridge re-start or after the iOS Home application has been re-started. After that it seems to work fine. If this after-restart delay is what you are experiencing, I haven't found a solution to that and think its probably normal for HomeKit.

**Comment by mugen5** [comment]
Everything you mentioned above I have done. Except update apple tv. I'll do that over the weekend and do more testing and see what happens.

**Comment by jvmahon** [comment]
Regarding the device updating delay, Homebridge was updated a couple of days ago to version 4.42 and now devices *seem* to update faster. You might also try that. To update homebridge, run:

      npm -g update

**Comment by mugen5** [comment]
Did the update and at the end got this message. "Update available 5.6.0 - 6.0.0 Run npm i npm to update. Which I did. Waited 3 hours checking periodically and devices were always showing not responding. Delete homebridge and tried to re add it but homekit is not seeing it. If I type homebridge in command prompt I do get the code and see devices updating so it is running.

**Comment by mugen5** [comment]
Thanks that worked to pair it again. I'll let you know if it improves my devices not responding issue.

**Comment by jvmahon** [comment]
Unfortunately, after some further testing, the "updating" delays seem about the same. My guess is this is on the "Apple" side of things (i.e., Apple TV or servers), rather than homebridge, but I can't be sure of that since my code is only at the plugin side of things, rather than all the code to support the plugin.
I'm closing this issue again. Good luck.

**Comment by mugen5** [comment]
When you say delay are you talking a few seconds? I have seen instances were I get "I didn't get a response from your devices" I then check the app and all devices are showing as not responding. This can last from several minutes to way longer.

**Comment by jvmahon** [comment]
I have seen these delays last up to a few minutes (not more than 5). Sometimes they resolve if I close the Home App and re-start. The delays are both for "native" HomeKit accessories as well as those that use Homebride. Since the delays aren't limited to HomeBridge, I'm assuming its something else at Apple that is the issue. I'm hoping the TVOS 11.4 / iOS 11.4 release (expected in a few weeks) will address this. It seems to me to be an overall weakness in HomeKit. Delays are generally the longest when I first start Home on the iPhone, but less when re-opening it.
