### ISSUE TITLE
HomeBridge SecuritySystem - how to use?

### ISSUE THREAD

**Issue by rrman** [jvmahon/homebridge-homeseer#43]
Hi,

I originally posted this question in HomeSeer (https://forums.homeseer.com/showthread.php?p=1364287#post1364287), but posting this issue per your response in the forum thread.

I've done online searches via Google and also searching in HomeSeer's forum, and I couldn't find an answer to this, so your input or additional documentation would be great.

The Homebridge HomeSeer plugin supports the following accessory:

{
"ref":230, // Required - HomeSeer Device Reference of a Security System
"type":"SecuritySystem", // Required for a security system
"name":"Home alarm", // Optional - HomeSeer device name is the default
"armedStayValues":[0], // Optional - List of the HomeSeer device values for a HomeKit security state=ARMED-STAY
"armedAwayValues":[1], // Optional - List of the HomeSeer device values for a HomeKit security state=ARMED-AWAY
"armedNightValues":[2], // Optional - List of the HomeSeer device values for a HomeKit security state=ARMED-NIGHT
"disarmedValues":[3], // Optional - List of the HomeSeer device values for a HomeKit security state=DISARMED
"alarmValues":[4], // Optional - List of the HomeSeer device values for a HomeKit security state=ALARM
"armStayValue":0, // Required - HomeSeer device control value to arm in stay mode. If you don't have this mode, select any value that arms your system
"armAwayValue":1, // Required - HomeSeer device control value to arm in away mode. If you don't have this mode, select any value that arms your system
"armNightValue":2, // Required - HomeSeer device control value to arm in night mode. If you don't have this mode, select any value that arms your system
"disarmValue":3 // Required - HomeSeer device control value to disarm security system
} 

There's no interface available that will allow HomeSeer to work with my real security system. However, I have a couple of Aeotec alarm devices that I'd like to have HomeSeer turn on or off based on events such as motion, doors being opened, etc. The Aeotec alarm devices basically just make a loud alarm sound when they are turned on.

I'm not sure how the Homebridge "SecuritySytem" device type works. Can someone show how they created a HomeSeer virtual device that's used with the "SecuritySystem" device type? And provide a description on the types of events that are needed to support this device type?

Thanks.

Randy (randman in HomeSeer forum)

**Comment by jvmahon** [comment]
I've added an initial explantion to the Wiki page, here: https://github.com/jvmahon/homebridge-homeseer/wiki/Setting-Up-the-SecuritySystem-Type

Let me know if this gives you enough guidance for now. I can add more if you need it. If I don't hear back, I'll close out this comment in a few days.

**Comment by jvmahon** [comment]
You're welcome.  Yes, setting Away is tricky if you are at home. The easiest solution is to set it from your iOS device after you exit the house and close the door.

Another solution would be to create another virtual device which is a simple switch, let's call it "Fully Armed". Whenever the virtual SecuritySystem device in HomeSeer goes to the "Off" alarm state, an event should activate to turn the "Full Armed" Switch to "Off". Then also create your security system events such that when "Away"is  selected, it triggers an event that first checks if any of the sensors area already triggered; if they are, return to the "Off" mode. Otherwise, start a countdown in that event, say 30 seconds using the HomeSeer "wait" event action, and then turn the "Fully Armed" switch to "On".  Now, in your sensor events, for the "Armed" state, you no longer check the virtual SecuritySystem device; instead you check this "extra" virtual switch device and  you would use the logic ((If fully_Armed is On) and (If sensor is triggered)) then set security system to "Triggered".   There are probably other ways to do it, but I think this one is pretty straightforward.

As for letting the user know that the SecuritySystem didn't arm because a sensor was already triggered, I don't know of any way to convey that via the Home app, but what you can do is to set HomeSeer to send your device a text if this occurs.  You can send a text via the HomeSeer email function. For example, to send a text to an AT&T subscriber with phone# 2125551212, you would send email to the phone number    2125551212@mms.att.net saying why the system didn't arm .  Most cellular providers have an email domain you can use for sending text. See, https://www.digitaltrends.com/mobile/how-to-send-a-text-from-your-email-account/

**Comment by jvmahon** [comment]
I've added the explanations in my prior email to the wiki entry. I haven't made much use of the SecuritySystem device, so I've only given brief thought to this.  If you come up with a better solution, let me know.

**Comment by jvmahon** [comment]
I'm going close out this comment for now. Re-Open if you need to ask anything else.
