### ISSUE TITLE
How to make incremental changes (addition, deletion) to config.json

### ISSUE THREAD

**Issue by rrman** [jvmahon/homebridge-homeseer#46]
While setting up my homebridge, whenever I've had a lot changes to config.json, I would:

1. stop homebridge 
2. remove the homebridge accessory from the iOS Home app
3. delete the persist and accessories folder 
4. start homebridge
5. add the homebridge accessory back using the iOS Home app

Aside: I actually run 4 homebridge services in my VM (helps minimize impacts when making lots of changes in one of the homebridge service's config.json).

Now that my configuration is somewhat stabilizing, having to do above steps is a pain when I only need to make small changes (like add, remove, or rename one or two accessories). 

My questions are, how to make incremental changes so that I don't have to "start from scratch" using the steps above; in particular, what is best/recommended way to just:

1. Remove one accessory from config.json 
2. Add just one accessory to config.json
3. How to rename an accessory (I guess I can just  rename it in the Home app, and to be consistent, rename in config.json).

Thanks,

Randy

**Comment by jvmahon** [comment]
This is more of a general homebridge issue, rather than with this plugin. I've had the same issue using both this and other plugins and have had to solve it in the same way that you are solving it. The best I can figure is it has something to do with the way HomeBridge identifies and tracks accessories using the uuid_base value.  As a rule, when adding / removing / changing a single accessory, I usually don't have the issue you mentioned and I think I experience fewer problems of this sort if I don't give the accessories names in the config.json (if you don't name them in config. json, then the plugin will name them as (room name) +"." + (homebridge device name).  

Maybe raise this issue in the homebridge application's issue section. Sorry I can't be of more assistance.

**Comment by rrman** [comment]
I did more testing. I noticed I can add (or remove) a device by just changing config.json and restarting homebridge. The device is automatically added (or removed) from HomeKit. Almost all my devices only specify the name of the device and its ref. I like specifying the name for two reasons: (1) serves as a "comment" in the config.json so I know what the device is for, and 
(2) I use the naming convention "room name device name", and when I add it to HomeKit and assign it to "room name", the device's icon shows up as "room name device name". If I rely on the default name, it will wind up showing up in HomeKit as "room name room name.device name".

Anyway, seems that in general, I can now add or remove single devices without having to blow everything away like I used to do. It's nice not having to reassign rooms and change status/notifications for all old devices.

Anyway, your 2018 plug-in has been great!!!! Thanks for creating this!

Randy
