### ISSUE TITLE
trouble accessing remote HomeSeer server

### ISSUE THREAD

**Issue by JoshKitson** [jvmahon/homebridge-homeseer#49]
I'm trying to configure the plugin to access a remote homeseer instance via a Dynamic DNS service.

host": "http://user:password@myDDNS.no-ip.net:8025",

port 8025 has a portfoward to the Homeseer's Web port, and port 11000 is forwarded to homeseer as well For ASCII interface

Strangely, this setup works perfectly when homebridge is on the same network as the Homeseer server, however but whenever it's on a different network returns [HomeSeer] 401 Undefined?
can't work out what i'm doing wrong.

**Comment by jvmahon** [comment]
The HomeSeer ASCII interface is telnet based, not HTTP and the plugin does not use the username / password for the telnet connection. It works locally because HomeSeer does not require username / password for connections coming from the local network.   What's happening in the code is that, in order to get the host information to establish the telnet connection, at  line 338 of the index.js file, the host information is parsed using parseUri to pull out the host's IP number. The IP number alone, and not username and password, is then used to make telnet connections at line 345 and, in case of error, to recover the telnet connection at line 390 of index.js.  Basically, what needs to be done is the code in these areas would need to be supplemented to also pull the username / password out of the host information and use that in making the telnet connection. Unfortunately, looking at the Javascript socket.connect function (https://nodejs.org/api/net.html#net_socket_connect ) I don't see how to pass username / password in the telnet connection. Maybe someone with more experience on Javascript telnet networking can take a look and help.

**Comment by JoshKitson** [comment]
Ok, I understand.
Would love to hear if anyone has a workaround for this?
So if get rid of the ASCII port and lose real-time updates will the plugin work?

**Comment by jvmahon** [comment]
In theory, if the ASCII port doesn't connect, it should fall back to using just the http:// port.

This makes me think that maybe you aren't even getting the http connection and that could be a problem with your HomeSeer setup and port forwarding on your router.  So test that first without the plugin.  To do so, just enter the following address in your browser, substituting in the correct user, password, IP address, etc:    

     http://user:password@myDDNS.no-ip.net:8025/JSON?request=getstatus

Do you get back a block of json formatted data (starts and ends with brackets and includes a bunch of field names and values between the brackets?  If not, there's a problem with your HomeSeer setup or your firewall or something else that needs to be fixed before you even bother trying to get the plugin to work.

**Comment by JoshKitson** [comment]
Your right, the issue was an incorrect password for the user account (I'd confused passwords between myhs accounts and local HS accounts).
This actually fixed the issue and plugin works perfectly with realtime updates this way. thanks for your help troubleshooting

**Comment by jvmahon** [comment]
You're welcome.
