### ISSUE TITLE
Feature request: energy usage support

### ISSUE THREAD

**Issue by RiggsUS** [jvmahon/homebridge-homeseer#67]
Is there any chance of adding energy usage support for viewing in apps like Eve.

**Comment by jvmahon** [comment]
I don't plan to  as there's a simple workaround that does enough for my purposes -- what I do is that I set up a "LightSensor" device and set its "ref" value to the reference of the HomeSeer "watts" device.  On the iOS Home app, it will then give you the watts value from Homeseer. The one limitation, is it will have the designation "lux" instead of "watts", but I find I can avoid confusion on this by simply giving the iOS Home device a name that includes the word "watts."  If Apple adds a Watts type to the "official" Homekit Accessory Protocol, I may revisit this.

**Comment by RienduPre** [comment]
Too bad, Elgato Eve have perfectly included this in their homekit products and app.

Any change you would reconsider your opinion.

Brest regards,
Rien

**Comment by jvmahon** [comment]
I believe Eve uses non-Apple Characteristic extensions for the Watts measurements which are not supported by homebridge and, accordingly, not supported by my plugin. I hope to see Apple add equivalent functionality at some point, and was disappointed it wasn't added in the iOS 12 update. If it gets up into a future release, then I'll try and add it, but at least for now, I'm not working on any non-Apple extensions.
