### ISSUE TITLE
Upgrade hohemebridge and plugin

### ISSUE THREAD

**Issue by goldriver2** [jvmahon/homebridge-homeseer#77]
I an looking at documentation on upgrading my windows installation to the latest version of the homebridge and the homebridge-homeseer plugin, can anyone guide me  please

**Comment by jvmahon** [comment]
Its generally pretty easy.

You can do it by entering the following in a console window:
   npm -g update

If you are going to do it, you may want to update to the latest nodejs from  www.nodejs.org which has some security fixes.

But, I haven't added anything substantive to the plugin in quite a while, and there have been no major bug fixes, so if its working O.K. for you, there  may be  no need to update -- i.e., if it ain't broke, do you really want to risk touching anything. Obviously, that's your call.

**Comment by goldriver2** [comment]
thanks for this, I am actually on 2.2 and looking at the new things, may be I might be better stay where I am for now

**Comment by jvmahon** [comment]
The changes since 2.2 are (mostly) explained on the github main page and include things like Window Coverings, stricter type checking, and he ability to customize "on" and "off" values.  If you already have a working config.json, then the type checking shouldn't matter to you and neither should the customization of "on" and "off" values.  If you don't have window coverings then that doesn't help you either.

So, unless you need one of the things I've outlined, I agree it may be better to leaving things alone.
